package com.ifinance.model;

import java.util.List;

import com.ifinance.model.base.BaseNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
	public static final News dao = new News().dao();
	
	/**
	 * 最新4条资讯
	 * @return
	 */
	public List<News> getTopZixun()
	{
		return dao.find("select * from news where type=0 order by id desc limit 0,4");
	}
	
	/**
	 * 最新4条税务
	 * @return
	 */
	public List<News> getTopShuiwu()
	{
		return dao.find("select * from news where type=1 order by id desc limit 0,4");
	}
	
	/**
	 * 最新4条问答
	 * @return
	 */
	public List<News> getTopFaq()
	{
		return dao.find("select * from news where type=2 order by id desc limit 0,4");
	}
}
